export const GAME_STATES = Object.freeze({
  MENU: "MENU",
  PLAYER_SETUP: "PLAYER_SETUP",
  PLAYER_AIM: "PLAYER_AIM",
  PLAYER_SHOT: "PLAYER_SHOT",
  CPU_THINK: "CPU_THINK",
  CPU_SHOT: "CPU_SHOT",
  ROUND_END: "ROUND_END",
  GAME_OVER: "GAME_OVER",
});
